### ISSUE TITLE
Problem with sending zcl to other wallet

### ISSUE THREAD

**Issue by cspek** [z-classic/zclassic#185] opened 2018-09-19 18:57 UTC
I use wallet !Z.1.0.3 on windows 7 or vista. I can't send zcl to other wallet because i got error: Server is not answer after 4 hours signing transaction. I have tried one time but after 3 hours signing transaction i just click exit this was waste of time.  i Have imported wallet by private key because on mac Wallet not working. Why i can't send ZCL  and everything operation is so long?

**Comment by VictorLux** [comment] 2018-09-19 21:54
Hi,
Did you change the server on network tabs ?
please see my screenshot.
Cheers,
Vic.
<img width="659" alt="capture d ecran 2018-09-19 a 23 52 54" src="https://user-images.githubusercontent.com/37399521/45783869-50ea8400-bc67-11e8-857e-3d2702f18593.png">

**Comment by cspek** [comment] 2018-09-20 06:12
Yes i did

**Comment by cspek** [comment] 2018-09-20 06:14
Also my income transactions are not confirmed and i dont know why. Blocks from electrum.zclassic.community aren't match with blockchain

**Comment by nimbosa** [comment] 2018-09-20 06:49
this is an Electrum Light Client Wallet you are using @cspek? then this is a duplicate of this one, on the right repository here: https://github.com/z-classic/electrum-zcl/issues/181

this one is for the full node Zclassic client, Thanks!
 for support please use Discord for faster reply: https://discord.gg/45NNrMJ

**Closed by nimbosa** 2018-09-20 06:49 UTC
Labels: invalid, question, support
